# Generated by Django 3.1.7 on 2021-03-18 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_task_api', '0003_auto_20210318_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie_imdb',
            name='title',
        ),
        migrations.AddField(
            model_name='movie_imdb',
            name='title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movie_task_api.movies_list'),
            preserve_default=False,
        ),
    ]
