# Generated by Django 3.1.7 on 2021-03-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_task_api', '0007_auto_20210318_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_imdb',
            name='list_id',
            field=models.ManyToManyField(to='movie_task_api.Movies_List'),
        ),
        migrations.AlterField(
            model_name='movies_list',
            name='title',
            field=models.ManyToManyField(to='movie_task_api.Movie_IMDB'),
        ),
    ]
