# Generated by Django 3.1.7 on 2021-03-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_task_api', '0009_remove_movie_imdb_list_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies_list',
            name='movie_id',
            field=models.ManyToManyField(to='movie_task_api.Movie_IMDB'),
        ),
        migrations.RemoveField(
            model_name='movies_list',
            name='title',
        ),
        migrations.AddField(
            model_name='movies_list',
            name='title',
            field=models.CharField(db_index=True, default=1, max_length=200),
            preserve_default=False,
        ),
    ]
